import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#040B21', // Deeper, richer background
        width: '100%',
      },
      gradientBackground: {
        ...StyleSheet.absoluteFillObject,
        opacity: 0.7,
      },
      content: {
        flex: 1,
        backgroundColor: 'transparent',
      },
      scrollContent: {
        flexGrow: 1,
      },
      header: {
        paddingTop: 56,
        paddingBottom: 40,
        alignItems: 'center',
        backgroundColor: 'rgba(15, 23, 42, 0.75)',
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
        marginBottom: 32,
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 16,
        elevation: 12,
        borderBottomWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
      },
      headerGlow: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 120,
        backgroundColor: 'rgba(99, 102, 241, 0.08)',
        borderRadius: 40,
        transform: [{ scale: 1.2 }],
        opacity: 0.6,
      },
      headerTitle: {
        fontSize: 42,
        color: '#FFFFFF',
        fontWeight: '800',
        letterSpacing: 1.2,
        textShadowColor: 'rgba(99, 102, 241, 0.6)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 6,
        marginBottom: 8,
      },
      headerSubtitle: {
        fontSize: 17,
        color: '#A5B4FC',
        letterSpacing: 0.8,
        opacity: 0.9,
        fontWeight: '500',
      },
      uploadButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#4F46E5',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 36,
        marginHorizontal: 24,
        marginBottom: 36,
        shadowColor: '#4F46E5',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.15)',
      },
      uploadButtonGradient: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 20,
        opacity: 0.8,
      },
      uploadText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
        marginLeft: 14,
        letterSpacing: 0.6,
      },
      videoSection: {
        marginHorizontal: 24,
        marginBottom: 36,
      },
      videoContainer: {
        backgroundColor: 'rgba(15, 23, 42, 0.8)',
        borderRadius: 32,
        overflow: 'hidden',
        height: 320,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 16,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
      },
      videoOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(99, 102, 241, 0.05)',
      },
      video: {
        flex: 1,
      },
      progressContainer: {
        marginHorizontal: 24,
        padding: 24,
        backgroundColor: 'rgba(99, 102, 241, 0.1)',
        borderRadius: 24,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
        alignItems: 'center',
      },
      progressBar: {
        width: '100%',
        height: 6,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 3,
        marginVertical: 16,
        overflow: 'hidden',
      },
      progressFill: {
        height: '100%',
        backgroundColor: '#4F46E5',
        borderRadius: 3,
      },
      progressText: {
        color: '#A5B4FC',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 0.6,
      },
      framesSection: {
        marginTop: 36,
        paddingLeft: 24,
      },
      sectionTitle: {
        fontSize: 24,
        color: '#FFFFFF',
        fontWeight: '700',
        marginBottom: 24,
        letterSpacing: 0.6,
        paddingRight: 24,
      },
      framesScrollContent: {
        paddingVertical: 16,
        paddingRight: 24,
      },
      frameItem: {
        width: 180,
        height: 135,
        marginRight: 20,
        borderRadius: 24,
        overflow: 'hidden',
        backgroundColor: 'rgba(15, 23, 42, 0.8)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 12 },
        shadowOpacity: 0.35,
        shadowRadius: 16,
        elevation: 12,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
      },
      frameItemGradient: {
        ...StyleSheet.absoluteFillObject,
        opacity: 0.1,
      },
      frameThumbnail: {
        width: '100%',
        height: '100%',
      },
      frameOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 16,
        backgroundColor: 'rgba(15, 23, 42, 0.9)',
        backdropFilter: 'blur(16px)',
        borderTopWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.15)',
      },
      frameTimestamp: {
        color: '#A5B4FC',
        fontSize: 14,
        fontWeight: '600',
        letterSpacing: 0.5,
      },
      summarySection: {
        marginTop: 36,
        marginHorizontal: 24,
        marginBottom: 32,
      },
      summaryCard: {
        backgroundColor: 'rgba(15, 23, 42, 0.8)',
        borderRadius: 32,
        padding: 28,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 16,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
      },
      summaryCardGradient: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 32,
        opacity: 0.1,
      },
      summaryText: {
        color: '#E0E7FF',
        fontSize: 17,
        lineHeight: 28,
        marginBottom: 28,
        letterSpacing: 0.4,
      },
      playButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#4F46E5',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 16,
        alignSelf: 'flex-start',
        shadowColor: '#4F46E5',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.15)',
      },
      playButtonGradient: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 16,
        opacity: 0.8,
      },
      playButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 10,
        letterSpacing: 0.5,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(4, 11, 33, 0.98)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContent: {
        width: '94%',
        maxHeight: '90%',
        backgroundColor: 'rgba(15, 23, 42, 0.95)',
        borderRadius: 36,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 20 },
        shadowOpacity: 0.5,
        shadowRadius: 28,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
      },
      modalGradient: {
        ...StyleSheet.absoluteFillObject,
        opacity: 0.1,
      },
      modalImage: {
        width: '100%',
        height: 360,
        backgroundColor: '#040B21',
      },
      modalCaptionContainer: {
        padding: 28,
        backgroundColor: 'rgba(15, 23, 42, 0.98)',
      },
      modalTimestamp: {
        color: '#A5B4FC',
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 14,
        letterSpacing: 0.5,
      },
      modalCaption: {
        color: '#E0E7FF',
        fontSize: 17,
        lineHeight: 28,
        letterSpacing: 0.4,
      },
      modalNavigation: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        position: 'absolute',
        top: '50%',
        left: 24,
        right: 24,
        transform: [{ translateY: -28 }],
      },
      navButton: {
        width: 56,
        height: 56,
        backgroundColor: 'rgba(99, 102, 241, 0.2)',
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.3)',
        shadowColor: '#4F46E5',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
      },
      navButtonGradient: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: 28,
        opacity: 0.2,
      },
      navButtonDisabled: {
        opacity: 0.3,
      },
      closeButton: {
        position: 'absolute',
        top: 24,
        right: 24,
        width: 44,
        height: 44,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.1)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
      },
      // Status bar styles
      statusBar: {
        backgroundColor: 'transparent',
        translucent: true,
      },
      // Loading indicator styles
      loadingIndicator: {
        color: '#4F46E5',
        size: 'large',
      },
      // Error state styles
      errorContainer: {
        padding: 20,
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        borderRadius: 16,
        marginHorizontal: 24,
        borderWidth: 1,
        borderColor: 'rgba(239, 68, 68, 0.2)',
      },
      errorText: {
        color: '#FCA5A5',
        fontSize: 15,
        textAlign: 'center',
        letterSpacing: 0.3,
      },
      audioControlsContainer: {
        marginTop: 20,
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        borderRadius: 20,
        padding: 16,
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.2)',
      },
      
      timeDisplay: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginBottom: 8,
      },
      
      timeText: {
        color: '#A5B4FC',
        fontSize: 14,
        fontWeight: '600',
      },
      
      progressBar: {
        height: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 2,
        marginVertical: 8,
        overflow: 'hidden',
      },
      
      progressFill: {
        height: '100%',
        backgroundColor: '#4F46E5',
        borderRadius: 2,
      },
      
      audioButtons: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 16,
        gap: 20,
      },
      
      audioButton: {
        width: 44,
        height: 44,
        backgroundColor: 'rgba(79, 70, 229, 0.4)',
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(99, 102, 241, 0.3)',
      },
      
      mainButton: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#4F46E5',
      },
    });