import { StyleSheet, Dimensions } from 'react-native';
import { colors, patterns, gradients } from '../theme';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  gradient: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 32,
  },
  content: {
    flex: 1,
    padding: 16,
  },
  header: {
    marginBottom: 32,
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: colors.backgroundAccent,
    borderWidth: patterns.headerBorderWidth,
    borderColor: colors.borderAccent,
    minHeight: 240,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  headerGradient: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.95,
  },
  headerContent: {
    padding: 28,
    alignItems: 'center',
    position: 'relative',
    zIndex: 1,
  },
  flagContainer: {
    position: 'absolute',
    top: -12,
    right: 24,
    transform: [{ rotate: '15deg' }, { scale: 1.1 }],
    zIndex: 2,
  },
  titleBorder: {
    marginTop: 24,
    marginBottom: 20,
    width: '95%',
    borderWidth: 2.5,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  titleContainer: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
  },
  titleMain: {
    fontSize: 44,
    fontWeight: '800',
    color: colors.textTertiary,
    marginBottom: 0,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
    letterSpacing: 1.2,
  },
  titlePlus: {
    fontSize: 26,
    fontWeight: '700',
    color: colors.secondary,
    marginBottom: 10,
    textShadowColor: colors.accent,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.8,
  },
  subtitle: {
    fontSize: 22,
    color: colors.textSecondary,
    fontWeight: '600',
    letterSpacing: 0.6,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  description: {
    fontSize: 17,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 26,
    paddingHorizontal: 24,
    marginTop: 20,
    fontWeight: '500',
    letterSpacing: 0.4,
  },
  decorativeLine: {
    width: '70%',
    height: 3,
    marginTop: 24,
    borderRadius: 1.5,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.borderAccent,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  featuresContainer: {
    marginBottom: 36,
    padding: 20,
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
    borderRadius: 28,
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderAccent,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  featureRow: {
    flexDirection: 'row',
    marginHorizontal: -10,
    marginBottom: 20,
    justifyContent: 'space-around',
    position: 'relative',
    zIndex: 1,
  },
  uploadContainer: {
    marginBottom: 36,
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: patterns.borderWidth * 1.5,
    borderColor: colors.borderAccent,
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
    position: 'relative',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
  },
  uploadButton: {
    overflow: 'hidden',
    borderRadius: 20,
    position: 'relative',
  },
  uploadButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  uploadContent: {
    padding: 36,
    alignItems: 'center',
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
  },
  uploadIcon: {
    marginBottom: 20,
    color: colors.secondary,
    transform: [{ scale: 1.4 }],
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  uploadButtonText: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.textTertiary,
    marginBottom: 10,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.6,
  },
  uploadSubtext: {
    fontSize: 16,
    color: colors.textSecondary,
    fontWeight: '500',
    letterSpacing: 0.4,
    textAlign: 'center',
    lineHeight: 24,
  },
  videoSection: {
    marginBottom: 36,
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
    borderRadius: 28,
    padding: 24,
    borderWidth: patterns.borderWidth * 1.5,
    borderColor: colors.borderAccent,
    position: 'relative',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },
  videoWrapper: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: colors.background,
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderLight,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  video: {
    width: '100%',
    aspectRatio: 16 / 9,
  },
  framesSection: {
    marginBottom: 32,
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
    borderRadius: 24,
    padding: 20,
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderAccent,
    position: 'relative',
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.textTertiary,
    marginBottom: 24,
    paddingHorizontal: 8,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.8,
  },
  frameCard: {
    marginBottom: 16,
    borderRadius: patterns.borderRadius,
    overflow: 'hidden',
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderLight,
    backgroundColor: colors.backgroundLight,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  frameCardGradient: {
    padding: 16,
  },
  frameCardContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  frameThumbnailContainer: {
    width: 130,
    height: 85,
    borderRadius: 12,
    overflow: 'hidden',
    marginRight: 12,
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderLight,
    backgroundColor: colors.backgroundLight,
  },
  frameThumbnail: {
    width: '100%',
    height: '100%',
  },
  thumbnailPlaceholder: {
    backgroundColor: colors.backgroundAccent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timestampBadge: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: colors.primary,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  timestampText: {
    color: colors.textTertiary,
    fontSize: 13,
    fontWeight: '700',
  },
  captionContainer: {
    flex: 1,
    paddingVertical: 8,
  },
  captionText: {
    color: colors.textTertiary,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  summarySection: {
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: 'rgba(220, 38, 38, 0.08)',
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderAccent,
    marginBottom: 32,
  },
  summaryCard: {
    padding: 24,
  },
  summaryText: {
    fontSize: 17,
    color: colors.textTertiary,
    lineHeight: 26,
    marginBottom: 24,
    letterSpacing: 0.3,
    fontWeight: '500',
  },
  audioControlsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    gap: 16,
  },
  playButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    backgroundColor: colors.primary,
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderLight,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  decorativeBorder: {
    borderWidth: patterns.borderWidth,
    borderColor: colors.borderLight,
    borderRadius: patterns.borderRadius,
    padding: 2,
    overflow: 'hidden',
  },
  decorativeAccent: {
    position: 'absolute',
    backgroundColor: colors.accent,
    opacity: 0.15,
    borderRadius: patterns.borderRadius,
  },
  decorativeContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    overflow: 'hidden',
  },
  mandalaPattern: {
    position: 'absolute',
    width: SCREEN_WIDTH * 2,
    height: SCREEN_WIDTH * 2,
    top: -SCREEN_WIDTH,
    left: -SCREEN_WIDTH / 2,
    opacity: 0.05,
  },
  nepaliPattern: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.1,
    zIndex: 0,
  },
  decorativeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.borderAccent,
    position: 'absolute',
  },
  decorativeCorner: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: colors.borderAccent,
    position: 'absolute',
  },
}); 